### GET request to example server
POST http://localhost:8081/realms/fazmerir/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=fazmerir-backend&
client_secret=8EO5H155jGYVnrMGTUFd8MTPyjOwB0vj&
username=eliane&
password=123456


> {%
    client.global.set("access_token", response.body.access_token);
%}


### listar despesas
GET http://localhost:8080/despesas
Authorization: Bearer {{access_token}}



### cadastrar despesas

POST http://localhost:8080/despesas
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "valorDespesa": 3.0,
  "descricaoDespesa": "descricaoDespesa",
  "statusDespesa": "PENDENTE"
}
###




